import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/store/providers/auth";
import { Toaster } from "@/components/ui/sonner"


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} bg-gray-950 antialiased h-full w-full`}
      >
        <AuthProvider>
        {children}
        <Toaster position="top-right" />
        </AuthProvider>
      </body>
    </html>
  );
}
